# Generated by Django 5.2.6 on 2025-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='product',
            field=models.CharField(choices=[('gigaerp', 'Giga ERP'), ('gigaaccounting', 'Giga Accounting'), ('gigaims', 'Giga IMS'), ('gigahrms', 'Giga HRMS')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
